### ISSUE TITLE
Get clerk user auth in Background or Content scripts

### ISSUE THREAD

**Issue by jellohouse** [clerk/clerk-chrome-extension-starter#4]
In my extension Popup i have the `<ClerkProvider>` component wrapping the app.

I'm able to login and use all the hooks from the popup and components in the popup.

But now i want to access the logged in user session from my content script and background script.

How can i achieve this?

**Comment by tolgaouz** [comment]
I also have a very similar use-case. Were you able to achieve what you needed @jellohouse?

**Comment by jellohouse** [comment]
I ended up using `const { getToken } = useAuth();` in my popup and then saving the result from `const userAuthToken = await getToken();`   to chrome localstorage.

Then in the background/content i just get the auth token from localstorage.

But ideally there would be another way provided by Clerk.

**Comment by tolgaouz** [comment]
Yes, I agree. Thank you for the reply @jellohouse!

**Comment by zacharyblank** [comment]
Isn't the issue with this that the token expires and there is no clean way to refresh it?

I have the same use case of needing auth in the background script.

Here is my flow:
1. user logins in on my website
2. The extension is already installed and running and I have a content script with <ClerkProvider> which then gets authenticated at the same time as the website session (because they're essentially on the same site as the content script is injected. into the site. The problem with this is that the cookies are set for this domain only, in theory. I am seeing that the content script stays authenticated on other sites but not all. I haven't found a pattern yet.
3. Having the content script authenticate is a bogus pattern IMO because the cookies are set on other domains (for each site the extension runs on) and very prone to leak/attack/etc.
4. Instead, the background script needs to auth and the content script uses the background script as a proxy to any protected resources.

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

We're not actively monitoring issues in starter repositories and as such I'd recommend asking your question either in [GitHub Discussions](https://github.com/orgs/clerk/discussions/categories/questions) or on our [Discord server](https://clerk.com/discord).

Thanks!

**Comment by jellohouse** [comment]
Agreed @zacharyblank . This is actually what i've tried to do now: Start the clerk instance from the background script.

Then in the popup I wanted to use `<ClerkProvider Clerk={clerk} navigate={(to) => navigate(to)}> .... </ClerkProvider>` where clerk is the instance from the background script. However, I'm getting an error from clerkjs that window is undefined from the background script. 

And yes, now I realized that I am facing this issue with my previous attempt/solution, the auth token is only valid for about a minute and then it stops working.

Still looking for a solution... open to any suggestions.

**Comment by zacharyblank** [comment]
I got this working with the following approach:

1. User installs extension and is taken to a website to authenticate. This is a regular 'ol Nextjs app using Clerk
2. The website sends a message to the window when authentication happens:

```
window.postMessage({
    isSignedIn: true
})
```
3. A content script in the extension is listening for this message:

```
window.addEventListener("message", async (event) => {
  if (event.data.isSignedIn) {
    const response = await sendToBackground({
      name: "set-session",
      body: document.cookie
    })
  }
})
```
4. That content script sends all the newly set cookie data to a background service worker to be persisted.
5. At this point the background service worker can interact with clerk via the backend API to do things like verify the session, etc.
6. Then, whenever a valid token is needed in the content script, the content script simply asks the background script for it and the background script can do whatever it needs to do to provide it. (pull it from storage, generate a new one using the Clerk Backend API, etc.)

I hope this helps!

**Comment by jellohouse** [comment]
Ok i see when i do `console.log(document.cookie)` from the content script, there is a cookie called `__clerk_db_jwt` 

Assuming i have that cookie value in my content/background scripts, how would i get a clerk auth token for the user logged in to my extension popup?

Is there a way to start a new clerk instance with that cookie and get the user auth token? 
Or any way to start clerk in the background with a session from the popup?

P.S. I don't have a website and i would like to avoid it if possible...

**Comment by zacharyblank** [comment]
You can likely get away with the same pattern without a hosted site of your own if you want to use chrome pages (hosted by the browser itself and packaged with your extension).

instead of `__clerk_db_jwt` look at the  `__session` cookie. Once you have that you can create any number of tokens for any jwt templates you want using the Clerk Backend API. This is what I do. Store the session ID in the background service and then generate a new token whenever one is needed and pass that new token to the content script.

This is part of a Clerk backend interface that I wrote that handles creating new tokens. It isn't perfect but hopefully gives you an idea:

```
import type { Clerk } from "./clerk"
import jwt from "jsonwebtoken"

export class Session {
  clerk: Clerk

  constructor(clerk: Clerk) {
    this.clerk = clerk
  }

  async getToken(template: string): Promise<{ jwt: string }> {
    var id: string
    try {
      id = (
        (await this.clerk.storage.get("session")) as {
          sid: string
        }
      ).sid
    } catch (e) {
      console.error("Invalid or no session found in local storage")
    }

    // check if there is an existing token first
    var token = await this.clerk.storage.get(`${template}_token`)

    if (token) {
      const decoded = jwt.decode(token)

      if (decoded.exp) {
        const currentTimestamp = Math.floor(Date.now() / 1000) // Convert milliseconds to seconds
        if (decoded.exp > currentTimestamp) {
          return { jwt: token }
        }
      } else {
        return { jwt: token }
      }
    }

    var { jwt: token } = (await this.clerk._makeRequest(
      `/sessions/${id}/tokens/${template}`,
      {},
      "POST"
    )) as { jwt: string }

    await this.clerk.storage.set(`${template}_token`, token)

    return { jwt: token }
  }

  async revoke(id: string) {
    this.clerk.storage.clear()
    return await this.clerk._makeRequest(`/sessions/${id}/revoke`, {}, "POST")
  }

  async get(id: string) {
    return await this.clerk._makeRequest(`/sessions/${id}`, {}, "GET")
  }
}
```

I am interested to know if you get it working!

**Comment by jellohouse** [comment]
Ok so i would need to call this endpoint `https://api.clerk.com/v1/sessions/{session_id}/verify`

Described here https://clerk.com/docs/reference/backend-api/tag/Sessions#operation/VerifySession

I tried setting the session ID in path and body `token` to the value of `__session` from the popup.

But i see the endpoint requires an auth token in headers. I tried setting auth as the `__clerk_db_jwt` but that didn't work...
I'm getting error 401 unauthorized.

How do i get the Bearer auth token for the request?

**Comment by zacharyblank** [comment]
Sorry for the delayed response. Call the Clerk Backend API with your clerk api token. Not the user's auth token :)

**Comment by shaezzy** [comment]
Please do not include your **secret key in your chrome extension's source code**!!

> Publishable key: This key should be used in your frontend code, can be safely shared, and does not need to be kept secret.
> Secret key: These are the secret keys to be used from your backend code. They are sensitive and should be deleted if leaked.

Chrome extensions entire source is available to the browser, allowing anyone to view the source and steal your client secret. 

The proper way to accomplish this in chrome extensions, native apps, mobile apps, SPA's etc where a client secret cannot be securely stored is using PKCE flow.

https://oauth.net/2/pkce/

It looks like Clerk does support PCKE now, but have not tried this myself.
https://clerk.com/docs/advanced-usage/clerk-idp

**Comment by shaezzy** [comment]
Following up here - was able to set this up by setting up OAuth2 provider using PCKE.

<ins>Client secrets should not be included in your chrome extensions source code</ins> (anyone can see the source in their browser and steal it). OAuth2 PKCE flow should be used for such applications.

## Setup a Clerk OAuth app
https://clerk.com/docs/advanced-usage/clerk-idp#create-an-o-auth-application-in-clerk
> To create an OAuth Application that uses the authorization code flow with proof of key exchange (PKCE), set public to true in the POST request body.
- The callback url should be a domain in host_permissions. I used a dummy path such as /callback that returns 200, with any type of response. The chrome extension doesn't use the response so that wont matter, but parses the query params from the url.
- Keep note of the returned values, they will be used later
- The oauth domain should be added to host_permissions

## Clerk settings
- Enable URL-based session syncing should be DISABLED as described in https://www.npmjs.com/package/@clerk/chrome-extension

## In background / service worker
### Create code verifier and code challenge:
```js
import { randomBytes, createHash, BinaryLike } from "crypto";

const base64URLEncode = (str: Buffer): string => {
  return str
    .toString("base64")
    .replace(/\+/g, "-")
    .replace(/\//g, "_")
    .replace(/=/g, "");
};

const getCodeVerifier = (): string => {
  const buffer = randomBytes(32);
  return base64URLEncode(buffer);
};

const sha256 = (buffer: BinaryLike): Buffer => {
  return createHash("sha256").update(buffer).digest();
};

const getChallenge = (verifier: string): string => {
  return base64URLEncode(sha256(verifier));
};

```

### Get authorization code
If the request redirects to the sign in page, it indicates the user is not signed in. You could then open a new tab to the sign in page, display notification, or show a sign in link in your popup's html, and attempt the flow again once user is signed in.

```js
const getCodeFromRedirectUrl = (url: string, state: string) => {
  const parsed = new URL(url);
  const params = new URLSearchParams(parsed.search);
  if (!params.get("state") || params.get("state") !== state) {
    console.log("State does not match. Abort", params.get("state"));
    return null;
  }
  return params.get("code");
};

const codeChallenge = getChallenge(codeVerifier);
const state = randomBytes(16).toString("hex");
const scope = "<your scopes>";
const clientId = "<your client id>";
const redirectUrl = "<your callback url>"
const url =
  `<YOUR OAUTH2 DOMAIN>/oauth/authorize` +
  `?response_type=code` +
  `&code_challenge=${codeChallenge}` +
  `&code_challenge_method=S256` +
  `&client_id=${clientId}` +
  `&redirect_uri=${encodeURIComponent(redirectUrl)}` +
  `&scope=${encodeURIComponent(scope)}` +
  `&state=${state}`;
try {
  const response = await fetch(url, {
    redirect: "follow",
  });
  if (response.redirected && response.url.startsWith(redirect_uri)) {
    return getCodeFromRedirectUrl(response.url, state);
  } else if (
    response.redirected &&
    response.url.startsWith("<your clerk sign in url>")
  ) {
    // Indicates the user is not signed in, prompt them to sign in via the browser. Attempt the auth flow again once done.
  }
```

### Exchange code for token
Use the code and codeVerifier from the previous request, the code should only be used once and exchanged for a token.
```js
const body =
  `grant_type=authorization_code` +
  `&client_id=${clientId}` +
  `&code_verifier=${codeVerifier}` +
  `&code=${code}` +
  `&redirect_uri=${redirectUrl}`;

const response = await fetch(
  `<YOUR OAUTH2 DOMAIN>/oauth/token`,
  {
    method: "POST",
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
    },
    body,
  }
);
const json = await response.json();
setTokenInStorage(json);
return json.access_token;
```

### Store access token, refresh token and expiry in storage:
There are a few different choices with their trade offs. If this information is compromised, the attacker could generate new access tokens with the refresh token. Refresh token reuse detection on server side mitigates some risk here but I'm not sure if Clerk has this implemented.

Ensure you have storage in manifest permissions

https://developer.chrome.com/docs/extensions/reference/api/storage

- `chrome.storage.local`: 
> Confidential user information should not be stored! The storage area isn't encrypted. 

Local storage is saved to the user's disk not encrypted, so it could be possible for this to be taken.

- `chrome.storage.session`: This is secure because it is in memory storage, but will require a user to be signed in again in the next browser session.

Looks like a secure storage has been proposed for extensions, this sounds like it would be the best option once available:
https://github.com/w3c/webextensions/issues/154

### Refresh token:
Retrieve the access token and expiry from storage, when expired, refresh the token
```js
const response = await fetch(
    `<YOUR OAUTH2 DOMAIN>/oauth/token`,
    {
      method: "POST",
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
      },
      body: `grant_type=refresh_token&client_id=${clientId}&refresh_token=${token.refresh_token}`,
    }
  );
  if (response.status === 200) {
    const json: Token = await response.json();
    setTokenInStorage(json);
    console.log("Refreshed token");
    return json.access_token;
  }
```

And done!

Your chrome extensions service worker should be able to refresh tokens and make authentication requests to your API. Your service worker can pass needed data to the other contexts.
